SELECT F.FLAVOR
FROM FIRST_HALF F
    INNER JOIN
    (
        SELECT FLAVOR
        FROM ICECREAM_INFO
        WHERE INGREDIENT_TYPE = 'fruit_based'
    ) I
    ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000
ORDER BY F.TOTAL_ORDER DESC;